# Generated by Django 3.1.1 on 2020-09-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWithUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_rendu', models.DateField(null=True)),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='TaskUser.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
