# Generated by Django 3.1.1 on 2020-09-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskUser', '0002_auto_20200925_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskwithuser',
            name='closed',
        ),
    ]
